### ISSUE TITLE
Cannot write NWB file

### ISSUE THREAD

**Issue by lfrank** [NeurodataWithoutBorders/pynwb#260]
Using either my own code or code directly cut and pasted from the Example on the documentation website produces an error upon trying to execute 

`io.write(nwbf)`

> Traceback (most recent call last):
  File "/Users/loren/Src/NWB/franklabnwb/convert_nspike.py", line 551, in <module>
    io.write(nwbf)
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.2.0.post0.dev14-py3.6.egg/pynwb/form/utils.py", line 306, in func_call
    return func(self, **parsed['args'])
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.2.0.post0.dev14-py3.6.egg/pynwb/form/backends/hdf5/h5tools.py", line 121, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.2.0.post0.dev14-py3.6.egg/pynwb/form/utils.py", line 212, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.2.0.post0.dev14-py3.6.egg/pynwb/form/utils.py", line 306, in func_call
    return func(self, **parsed['args'])
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.2.0.post0.dev14-py3.6.egg/pynwb/form/backends/io.py", line 38, in write
    f_builder = self.__manager.build(container, source=self.__source)
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.2.0.post0.dev14-py3.6.egg/pynwb/form/utils.py", line 306, in func_call
    return func(self, **parsed['args'])
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.2.0.post0.dev14-py3.6.egg/pynwb/form/build/map.py", line 37, in build
    result = self.__type_map.build(container, self, source=getargs('source', kwargs))
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.2.0.post0.dev14-py3.6.egg/pynwb/form/utils.py", line 306, in func_call
    return func(self, **parsed['args'])
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.2.0.post0.dev14-py3.6.egg/pynwb/form/build/map.py", line 990, in build
    attr_map = self.get_map(container)
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.2.0.post0.dev14-py3.6.egg/pynwb/form/utils.py", line 306, in func_call
    return func(self, **parsed['args'])
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.2.0.post0.dev14-py3.6.egg/pynwb/form/build/map.py", line 940, in get_map
    raise ValueError("class %s does not mapped to a data_type" % container_cls)
ValueError: class <class 'pynwb.file.NWBFile'> does not mapped to a data_type

**Comment by jcfr** [comment]
Hi Loren,

Do you experience issue using the release of pynwb ?

It looks like you are installing the project from the current GitHub source.

pip uninstall pynwb
pip install pynwb==0.2.0

**Comment by lfrank** [comment]
Thanks for checking, and indeed I was using it from the GitHub source, but I just installed using pip and I get the same error.   The code that replicates it is below (taken from the website, but with one error fixed; see my other recently posted documentation issue).

```
from datetime import datetime
from pynwb import NWBFile

f = NWBFile('the PyNWB tutorial', 'my first synthetic recording', 'EXAMPLE_ID', datetime.now(),
            experimenter='Dr. Bilbo Baggins',
            lab='Bag End Labatory',
            institution='University of Middle Earth at the Shire',
            experiment_description='I went on an adventure with thirteen dwarves to reclaim vast treasures.',
            session_id='LONELYMTN')
from pynwb.form.backends.hdf5 import HDF5IO

io = HDF5IO(filename, mode='w')
io.write(f)
io.close()
```

**Comment by jcfr** [comment]
Thanks for pointing this out. We will soon have all examples tested. See #262

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/NeurodataWithoutBorders/pynwb/commit/3a03d4ae63d81d3eb25c1d78d091756db919c659

@lfrank  Examples related to Creating and Writing Nwb files have been updated to following the current NWB convention are now tested.

Note that examples associated with Extending and validating  NWB files still need to go through the same process.

**Comment by lfrank** [comment]
@ajtritt @oruebel Andrew and Oliver - sorry to bother you with this, but the documentation for the extensions is still incorrect.  An an example, 

> spec = NWBAttributeSpec('bar', 'float', 'a value for bar')

should be (I believe)

> spec = NWBAttributeSpec('bar', 'a value for bar', 'float')

I'm not sure which other parts of the documentation are problematic, but a single pass through should be enough to find the errors and fix them, I think...

**Comment by neuromusic** [comment]
Running into this issue myself, after installing from pip. 

I'm reopening this issue because according to this PR https://github.com/NeurodataWithoutBorders/pynwb/pull/171 the code snippet @lfrank shared should work. The user shouldn't have to load get_manager then call it just to save the file. The documentation isn't the only problem here.

see https://gist.github.com/ajtritt/11f2bda4846a96eb67cd9e9a7e1b2bdc#file-io_scenarios-py-L46

These "scenarios" should be documented and tested, no?

**Comment by neuromusic** [comment]
to clarify, here's the snippet that fails for me:

``` Python
import datetime as dt
from pynwb import NWBFile
NA = 'THIS FIELD INTENTIONALLY LEFT BLANK'
nwb_file = NWBFile(
    source = NA, 
    session_description = NA, 
    identifier = NA, 
    session_start_time = dt.datetime.now(),
)

from pynwb import HDF5IO
io = HDF5IO('demo.nwb',mode='w')
io.write(nwb_file)
io.close()
```
according to the PR I linked to above, this should be supported.

looking more closely at the commit where @ajtritt implemented the feature, it looks like the feature works on a class called `NWBHDF5IO` that is a subclass of `HDF5IO`
https://github.com/NeurodataWithoutBorders/pynwb/pull/171/commits/540ff6a260f9d87fdabf3e6912b3cfe885a5845d#diff-a3ca34a73c95c6c1e20bae303cf04a97R147

here's the current line:
https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/__init__.py#L178

indeed, the following works
``` Python
import datetime as dt
from pynwb import NWBFile
NA = 'THIS FIELD INTENTIONALLY LEFT BLANK'
nwb_file = NWBFile(
    source = NA, 
    session_description = NA, 
    identifier = NA, 
    session_start_time = dt.datetime.now(),
)

from pynwb import NWBHDF5IO
io = NWBHDF5IO('demo.nwb',mode='w')
io.write(nwb_file)
io.close()
```
